In [15]:
import sys
import os

# localizar caminho automaticamente
import pandas as pd

from rdkit import RDConfig
sys.path.append(os.path.join(RDConfig.RDContribDir, 'SA_Score'))

import sascorer
from rdkit import Chem

In [16]:
# ===== CONFIGURAÇÕES =====
# Defina aqui os caminhos e parâmetros

# Diretório base
base_dir = '/Users/francisco/Documents/Scripts/DeNovo_HsDHODH/LigBuilder_Results/Build_HsDHODH_HIGHDIV_MAY/result/process_HsDHODH/'

# Arquivo de entrada
input_file = base_dir + 'dados_sem_duplicatas.csv'

# Arquivos de saída
output_file_completo = base_dir + 'dados_com_sa_score.csv'
output_file_filtrado = base_dir + 'dados_sa_score_filtrado.csv'

# Nome da coluna de SMILES
coluna_smiles = 'SMILES'

# Threshold do SA Score (moléculas com SA Score < threshold receberão valor 1)
threshold = 6.0
# =========================

In [17]:
# Carregar o dataset
df = pd.read_csv(input_file)

print(f"Dataset carregado: {len(df)} linhas")
df.head()

Dataset carregado: 410 linhas

,SMILES,Name,InChI,Formula,MW,LogP,pKd,Structure,Synthesize,Chemical
0,Oc1ccnn1CCc1cc(c(c(c1)F)ON)c1nc([nH]c1)C(=O)NC,27/000000362,InChI=1S/C16H17FN6O3/c1-19-16(25)15-20-8-12(22...,C16H17N6O3F,360,0.87,6.11,4.01,3.58,-160
1,SCS(=O)(=O)CCc1cc(c(c(c1)F)ON)c1nc([nH]c1)C(=O)NC,27/000000520,InChI=1S/C14H17FN4O4S2/c1-17-14(20)13-18-6-11(...,C14H17N4O4S2F,388,0.46,5.87,3.83,3.58,-160
2,NOc1c(F)cc(cc1c1nc([nH]c1)C(=O)NC)CC/C=C\C,27/000000289,InChI=1S/C16H19FN4O2/c1-3-4-5-6-10-7-11(14(23-...,C16H19N4O2F,318,1.48,5.78,3.66,3.58,-200
3,NOc1c(F)cc(cc1c1nc([nH]c1)C(=O)NC)CCc1[nH]ccc1,27/000000324,InChI=1S/C17H18FN5O2/c1-20-17(24)16-22-9-14(23...,C17H18N5O2F,343,1.07,5.77,3.82,3.58,-140
4,NOc1c(F)cc(cc1c1nc([nH]c1)C(=O)NC)CCCCC,27/000000433,InChI=1S/C16H21FN4O2/c1-3-4-5-6-10-7-11(14(23-...,C16H21N4O2F,320,1.89,5.76,3.42,3.58,-200

In [18]:
# Função para calcular o SA Score
def calculate_sa_score(smiles):
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is not None:
            return sascorer.calculateScore(mol)
        else:
            return None
    except:
        return None

# Aplicar a função na coluna de SMILES
df['SA_Score'] = df[coluna_smiles].apply(calculate_sa_score)

# Criar coluna binária baseada no threshold
df['SA_Score_Binary'] = (df['SA_Score'] < threshold).astype(int)

# Visualizar resultado
df.head()

[15:51:33] Explicit valence for atom # 16 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 16 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 20 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 12 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 12 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 12 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 2 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 14 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 12 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 19 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 16 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 16 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 8 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 13 N, 4, is greater than permitted
[15:51:33] Explicit valence for atom # 8 N, 4, is greater than permitted

,SMILES,Name,InChI,Formula,MW,LogP,pKd,Structure,Synthesize,Chemical,SA_Score,SA_Score_Binary
0,Oc1ccnn1CCc1cc(c(c(c1)F)ON)c1nc([nH]c1)C(=O)NC,27/000000362,InChI=1S/C16H17FN6O3/c1-19-16(25)15-20-8-12(22...,C16H17N6O3F,360,0.87,6.11,4.01,3.58,-160,3.554404,1
1,SCS(=O)(=O)CCc1cc(c(c(c1)F)ON)c1nc([nH]c1)C(=O)NC,27/000000520,InChI=1S/C14H17FN4O4S2/c1-17-14(20)13-18-6-11(...,C14H17N4O4S2F,388,0.46,5.87,3.83,3.58,-160,3.693340,1
2,NOc1c(F)cc(cc1c1nc([nH]c1)C(=O)NC)CC/C=C\C,27/000000289,InChI=1S/C16H19FN4O2/c1-3-4-5-6-10-7-11(14(23-...,C16H19N4O2F,318,1.48,5.78,3.66,3.58,-200,3.457394,1
3,NOc1c(F)cc(cc1c1nc([nH]c1)C(=O)NC)CCc1[nH]ccc1,27/000000324,InChI=1S/C17H18FN5O2/c1-20-17(24)16-22-9-14(23...,C17H18N5O2F,343,1.07,5.77,3.82,3.58,-140,3.435436,1
4,NOc1c(F)cc(cc1c1nc([nH]c1)C(=O)NC)CCCCC,27/000000433,InChI=1S/C16H21FN4O2/c1-3-4-5-6-10-7-11(14(23-...,C16H21N4O2F,320,1.89,5.76,3.42,3.58,-200,3.141805,1

In [19]:
# Contar quantos 1s e 0s na coluna binária
contagem = df['SA_Score_Binary'].value_counts().sort_index()
print(contagem)

SA_Score_Binary
0     15
1    395
Name: count, dtype: int64

In [20]:
# Salvar dataset completo com SA Score
df.to_csv(output_file_completo, index=False)
print(f"Dataset completo salvo em: {output_file_completo}")

Dataset completo salvo em: /Users/francisco/Documents/Scripts/DeNovo_HsDHODH/LigBuilder_Results/Build_HsDHODH_HIGHDIV_MAY/result/process_HsDHODH/dados_com_sa_score.csv

In [21]:
# Filtrar apenas moléculas com SA_Score_Binary = 1 (SA Score < threshold)
df_filtered = df[df['SA_Score_Binary'] == 1].copy()

print(f"Total de moléculas filtradas: {len(df_filtered)} (SA Score < {threshold})")

# Salvar o dataframe filtrado em CSV
df_filtered.to_csv(output_file_filtrado, index=False)

print(f"Arquivo filtrado salvo em: {output_file_filtrado}")

Total de moléculas filtradas: 395 (SA Score < 6.0)
Arquivo filtrado salvo em: /Users/francisco/Documents/Scripts/DeNovo_HsDHODH/LigBuilder_Results/Build_HsDHODH_HIGHDIV_MAY/result/process_HsDHODH/dados_sa_score_filtrado.csv